### ISSUE TITLE
Add missing features

### ISSUE THREAD

**Issue by kalsifer-742** [Kalsifer-742/eagletrt-recruiting-sw-microcontrollers#3]
Serial communication:
- [x] acquisition timings
- [x] leds status

LDR:
- [x] check values, noticed something strange happening
- [x] check if luxs have a maximum. (values collected have to be in spec)

**Comment by Kalsifer-742** [comment]
All corrections made.
The lux scale does not have a maximum value.

**Comment by kalsifer-742** [comment]
All corrections made.
The lux scale does not have a maximum value.
